openapi: 3.0.0
info:
  title: dhfood
  version: '1.0'
  contact:
    name: FinTech Product Team
    url: 'https://dhfintechproduct.com'
    email: fintechproduct@gmail.com
  termsOfService: 'https://dhfintechproduct.com/terms'
  description: Create account for user on dh platform
servers:
  - url: 'https://api.deliveryhero.com/fooddelivery/wallet'
    description: test
paths:
  /create-account-user:
    parameters: []
    post:
      summary: Create Account User
      operationId: create-account-user
      responses:
        '200':
          description: Account Created
      description: Create user account
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          required: true
          name: ' phoneNumber'
          description: |
            Phone number associated with wallet(required)
        - schema:
            type: string
          in: query
          name: ' secretKey'
          required: true
          description: |
            Developer secret key(required)
      tags:
        - wallet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                  example: '678922105'
                secretKey:
                  type: string
                  example: hfucj5jatq8h
              required:
                - phoneNumber
                - secretKey
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: wallet endpoints
  - name: wallet
