openapi: 3.0.0
info:
  title: dhfood
  version: '1.0'
  contact:
    name: FinTech Product Team
    url: 'https://dhfintechproduct.com'
    email: fintechproduct@gmail.com
  termsOfService: 'https://dhfintechproduct.com/terms'
  description: Create account for user on dh platform
servers:
  - url: 'https://api.deliveryhero.com/fooddelivery/wallet'
    description: test
paths:
  /create-account-user:
    get:
      summary: Create Account User
      tags:
        - wallet endpoints
      responses: {}
      operationId: create-account-user
      description: Create User account
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: ' phoneNumber'
          description: |
            Phone number associated with wallet(required)
          required: true
        - schema:
            type: string
          in: query
          name: secretKey
          description: |

            Developer secret key(required)
          required: true
    parameters: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: wallet endpoints
